[package]
name = "form-state"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "form-state"
src = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"]}
tokio = { version = "1", features = ["full"] } 
serde = { version = "1", features = ["derive"] }
shared = { path = "../form-net/shared/" }
serde_json = "1"
ditto = { path = "../../external/ditto" }
crdts = "7"
ipnet = { version = "2.4", features = ["serde"] }
axum = "0.8"
reqwest = { version = "0.12", features = ["json"]}
