[package]
name = "form-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bollard = "0.18"
tar = "0.4"
flate2 = "1"
tempfile = "3"
sha3 = "0.10"
rand = "0.8"
base64 = "0.22"
sha-crypt = "0.5"
lazy_static = "1"
