[package]
name = "form-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { "version" = "4.5", features=["derive"] }
#TODO: Reduce dependencies to individual alloy crates
# once we know what we will and wont need
alloy = { "version" = "0.9", features = ["full"]}
alloy-signer-local = { version = "0.9", features = ["mnemonic"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
sha3 = "0.10.8"
hex = "0.4.3"
random_word = { version = "0.4.3", features = ["en"] }
form-types = { path = "../form-types" }
