[package]
name = "form-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "form"
path = "src/main.rs"

[features]
testnet = []
devnet = []
mainnet = []

[dependencies]
clap = { "version" = "4", features=["derive"] }
#TODO: Reduce dependencies to individual alloy crates
# once we know what we will and wont need
clap_complete = "4"
colored = "2"
dialoguer = { version = "0.10", default-features = false }
alloy = { "version" = "0.9", features = ["full"]}
alloy-signer-local = { version = "0.9", features = ["mnemonic"] }
reqwest = { version = "0.12", features = ["json", "multipart", "stream"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha3 = "0.10"
hex = "0.4"
random_word = { version = "0.4", features = ["en"] }
vmm-service = { path = "../form-vmm/vmm-service" }
form-types = { path = "../form-types" }
form-pack = { path = "../form-pack" }
tokio-util = "0.7"
bytes = "1"
