# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust for Linux
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install Linux Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools gcc-multilib gcc-x86-64-linux-gnu

      - name: Build Linux Binaries
        run: |
          cargo build --release --bin form --target x86_64-unknown-linux-gnu --features treehacks
          cargo build --release --bin formnet-up --target x86_64-unknown-linux-gnu
          mkdir -p artifacts
          cp target/x86_64-unknown-linux-gnu/release/form artifacts/form-linux-x86_64
          cp target/x86_64-unknown-linux-gnu/release/formnet-up artifacts/formnet-up-linux-x86_64

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: artifacts/

  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust for macOS
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Build macOS Binaries
        run: |
          cargo build --release --bin form --target aarch64-apple-darwin --features treehacks
          cargo build --release --bin formnet-up --target aarch64-apple-darwin
          mkdir -p artifacts
          cp target/aarch64-apple-darwin/release/form artifacts/form-darwin-arm64
          cp target/aarch64-apple-darwin/release/formnet-up artifacts/formnet-up-darwin-arm64

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifacts
          path: artifacts/

  release:
    name: Release
    needs:
      - build-linux
      - build-macos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-artifacts
          path: artifacts

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-artifacts
          path: artifacts

      - name: Copy Binaries to Docs Directory
        run: |
          mkdir -p docs/install
          mkdir -p docs/install/form
          cp artifacts/form-* docs/install/
          cp artifacts/formnet-up-* docs/install/
          cp .github/install.sh docs/install/form/install.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docs/install/form-*
            docs/install/formnet-up-*
          prerelease: false
          generate_release_notes: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true

